$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: red
endpoint_name: credit-endpoint-3
model: 
    name: credit_defaults_model
    path: credit_defaults_model/credit_defaults_model
    type: mlflow_model
environment: azureml:aigbb-aml-bootcamp-dep-env@latest
code_configuration:
  code: src
  scoring_script: score.py
instance_type: Standard_DS3_v2
instance_count: 1
