$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

display_name: 04a_Pipeline_DataPrep_Train_CLI_Pipeline
description: Pipeline with 2 component jobs with data dependencies

settings:
  default_compute: azureml:cpu-cluster

outputs:
  final_model:
    mode: upload

jobs:
  component_data_prep:
    type: command
    component: azureml:data_prep_component@latest
    inputs:
      data: 
        type: uri_file
        path: azureml:credit_cards@latest
      test_train_ratio: 0.25
      train_data_csv: train 
      test_data_csv: test
    outputs:
      train_data_csv: 
        mode: upload
      test_data_csv: 
        mode: upload
  component_train:
    type: command
    component: azureml:train_credit_defaults_component@latest
    inputs:
      train_data_csv: ${{parent.jobs.component_data_prep.outputs.train_data_csv}}
      test_data_csv: ${{parent.jobs.component_data_prep.outputs.test_data_csv}}
      learning_rate: 0.2
      registered_model_name: credit_default_model
    outputs:
      model: ${{parent.outputs.final_model}}
