$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: ../src
command: >-
  python train.py 
  --data ${{inputs.data}} 
  --test_train_ratio ${{inputs.test_train_ratio}} 
  --learning_rate ${{inputs.learning_rate}} 
  --registered_model_name ${{inputs.registered_model_name}}
inputs:
  data: 
    type: uri_file
    path: azureml:credit_cards@latest
  test_train_ratio: 0.2
  learning_rate: 0.25
  registered_model_name: credit_default_model
environment: azureml:aigbb-aml-bootcamp-environment@latest
compute: azureml:cpu-cluster
display_name: 03a_Train_Model_CLI_Job
experiment_name: aigbb-aml-bootcamp
description: Train a Machine Learning model using a workspace Data asset.
