$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: ../src
command: >-
  python main.py 
  --data ${{inputs.data}} 
  --test_train_ratio ${{inputs.test_train_ratio}}               
  --learning_rate ${{inputs.learning_rate}}                    
  --registered_model_name ${{inputs.registered_model_name}}
inputs:
  data: 
    type: uri_file
    path: azureml:credit_cards@latest
  test_train_ratio: 0.2
  learning_rate: 0.25
  registered_model_name: credit_model_e2e_cli
environment: azureml:credit_train_cli_env@latest
#environment: 
#  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest
#  conda_file: conda.yml #### <--- CONDA.YML
compute: azureml:cpu-cluster-test #### <---- COMPUTE RESOURCE
display_name: Credit Card Demo
experiment_name: credit-card-demo-experiment
description: Train a model on credit card dataset
