$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: aigbb-aml-bootcamp-dep-env
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
conda_file: deployment_conda.yml
description: Environment created from a Docker image plus Conda environment.
